[phases.setup]
nixPkgs = [
    'python39',
    'python39Packages.pip',
    'python39Packages.setuptools',
    'python39Packages.wheel'
]

[phases.build]
cmds = [
    'pip3 install --break-system-packages --no-cache-dir -r src/requirements.txt'
]

[start]
cmd = 'cd src && uvicorn main:app --host 0.0.0.0 --port $PORT --log-level debug'