[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip']

[phases.build]
cmds = [
  'cd src',
  'pip install --upgrade pip',  # Langsung gunakan pip yang disediakan Nix
  'pip install --no-cache-dir -r requirements.txt'
]

[start]
cmd = 'cd src && uvicorn main:app --host 0.0.0.0 --port $PORT'
workdir = 'src'
