[phases.setup]
nixPkgs = ['python39']

[phases.install]
cmds = ['python -m ensurepip --upgrade']

[phases.build]
cmds = [
  'pip install --no-cache-dir fastapi uvicorn',
  'pip install --no-cache-dir -r src/requirements.txt'
]

[start]
cmd = 'cd src && PYTHONPATH=/app/src uvicorn main:app --host 0.0.0.0 --port $PORT'