[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip']

[phases.install]
cmds = ['python -m pip install --upgrade pip']

[phases.build]
cmds = [
  'ls -la',  # untuk debug
  'pwd',     # untuk debug
  'pip install --break-system-packages --no-cache-dir -r src/requirements.txt'
]

[start]
cmd = 'uvicorn main:app --host 0.0.0.0 --port $PORT'