[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip']

[phases.build]
cmds = [
  'pip install --break-system-packages --no-cache-dir -r src/requirements.txt'
]

[start]
cmd = 'uvicorn main:app --host 0.0.0.0 --port $PORT'