[phases.setup]
nixPkgs = [
    'python39',
    'python39Packages.pip',
    'python39Packages.setuptools',
    'python39Packages.wheel'
]

[phases.build]
cmds = [
    'mkdir -p /app/src',
    'cp -r src/* /app/src/',
    'cd /app/src && pip3 install --break-system-packages --no-cache-dir -r requirements.txt'
]

[start]
cmd = 'cd /app/src && uvicorn main:app --host 0.0.0.0 --port $PORT --log-level debug'
workdir = '/app/src'