[build]
builder = "nixpacks"

[deploy]
startCommand = "cd src && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
# Memastikan versi Python sesuai dengan setup Nixpacks
PYTHON_VERSION = "3.9"
PIP_BREAK_SYSTEM_PACKAGES = "1"
