[build]
builder = "nixpacks"

[deploy]
startCommand = "cd src && PYTHONPATH=/app/src uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "on_failure"
healthcheckInterval = 30
healthcheckMaxRetries = 3

[env]
PYTHON_VERSION = "3.9"
PORT = "8000"