[build]
builder = "nixpacks"

[deploy]
startCommand = "cd src && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/II3160"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
PYTHON_VERSION = "3.9"