[build]
builder = "nixpacks"

[deploy]
startCommand = "cd src && uvicorn main:app --host 0.0.0.0 --port $PORT --log-level debug --reload-dir src"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
healthcheckInterval = 15
healthcheckMaxRetries = 5

[env]
PYTHON_VERSION = "3.9"
PORT = "8000"
PYTHONPATH = "/app/src"
PYTHONUNBUFFERED = "1"
LOG_LEVEL = "debug"