[build]
builder = "nixpacks"

[deploy]
startCommand = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT --log-level debug"
healthcheckPath = "/minimal-health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
healthcheckInterval = 15
healthcheckMaxRetries = 3

[env]
PYTHON_VERSION = "3.9"
PORT = "8000"