[phases.setup]
nixPkgs = ['python310', 'python310Packages.pip', 'python310Packages.setuptools', 'python310Packages.wheel']

[phases.install]
cmds = [
  'python3 -m pip install --user --upgrade pip'
]

[phases.build]
dependsOn = ['install']
cmds = [
  'cd src',
  'python3 -m pip install --no-cache-dir -r requirements.txt'
]

[start]
cmd = 'cd src && python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT'