[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120"
healthcheckPath = "/minimal-health"
healthcheckTimeout = 180
restartPolicyType = "on_failure"
healthcheckInterval = 45
healthcheckMaxRetries = 5

[env]
PYTHON_VERSION = "3.9"
PORT = "8000"
WORKERS = "4"